dejima_tables:
    ShareWithInsurance:
      peers:
        - "dejima-gov-peer.dejima-net"
        - "dejima-insurance-peer.dejima-net"
    ShareWithBank:
      peers:
        - "dejima-gov-peer.dejima-net"
        - "dejima-bank-peer.dejima-net"
base_tables:
  GovernmentUser:
    dejima_table:
      - "ShareWithInsurance"
      - "ShareWithBank"
  BankUser:
    dejima_table:
      - "ShareWithBank"
  InsuranceUser:
        dejima_table:
          - "ShareWithInsurance"
peer_types:
  government:
    base_table:
      - "GovernmentUser"
  bank:
    base_table:
      - "BankUser"
  insurance:
    base_table:
      - "InsuranceUser"
