#! /bin/bash

set -e

if [ -d ".git/" ]; then
  # hook in git pre-commit
  if [ ! -L .git/hooks/pre-commit ]; then
    echo "Install Git hook ..."
    mkdir -p .git/hooks
    ln -sf ../../misc/admin/git/pre-commit .git/hooks/pre-commit
  fi
fi

# Start server
bundle check || bundle install

# create db if it does not exist
bundle exec rake db:exists || bundle exec rake db:create

# remove old server pid file, so we can boot multiple instances at once with volume: ["peer:/peer"]
bundle exec rails db:migrate && rm -f /peer/tmp/pids/server.pid && bundle exec rails server