CREATE EXTENSION pgrowlocks;

CREATE TABLE BT (
	ID	INT,
	A	INT,
	B	INT,
	C	INT,
	D 	INT
);

\echo 'LOADING bt'
INSERT INTO bt VALUES
(1, 8, -10, 15, 13);

CREATE TABLE BT_LINEAGE (
		ID		INT PRIMARY KEY,
        LINEAGE VARCHAR(80)
	);

\echo 'LOADING bt_lineage'
INSERT INTO bt_lineage VALUES
(1,'<PeerA,bt,1>');